### PR TITLE
use `pump` to capture all errors in map piping

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by gmaclennan** [comment]
Does this definitely work with big exports? I had lots of problems with strange stuff in streams so just want to make sure this doesn't break things.

**Comment by okdistribute** [comment]
In both this branch's version and on master, I was able to successfully download a png map with 10k x 10k px, which resulted in a 7.5MB file. 

map- -7 1354 57 9095 -6 1357 58 516 -1000mmx1000mm-288dpi 2

However, on my machine (Ubuntu 18.04.1 with Chromium) I wasn't able to open the png file (in multiple programs), getting this error:

screenshot from 2019-01-08 11-49-36

Seems like a minor issue, but I'll flag it in a new issue just in case anyone else comes across it.

**Comment by okdistribute** [comment]
Could be a problem with my version of Chromium? It should exist in a separate issue and isn't related to this PR.

**Comment by gmaclennan** [comment]
The attached image opens fine on my Macbook Pro. Maybe it's an issue with the png format being returned by [png-stream](https://www.npmjs.com/package/png-stream) or maybe it's an issue with the large size? Have you tried opening the PNG with chrome?

**Comment by okdistribute** [comment]
Yep, it opens only in Chromium

**Comment by gmaclennan** [comment]
Merging this, since it seems fine. Let's open a new issue. Do smaller exports have the same problem?

**Pull request merged**
